import { media } from "@/lib/media";
import type { Procedure, SpecialtyPage } from "@/types";

function p(name: string, ...points: string[]): Procedure {
  return { name, points };
}

export const modernMedicine = {
  documentTitle: "Modern Medicine – New Journey Health",
  path: "/modern-medicine-2/",
  heroTitle: "Advanced, Evidence-Based Care Across Specialties",
  heroBody:
    "Modern medicine brings together cutting-edge technology, globally trained specialists, and patient-focused care pathways to deliver safe, effective, and timely treatment. From diagnosis to recovery, our approach ensures precision, comfort, and continuity at every stage of your healthcare journey.",
  specialtiesHeading: "Our Specialties",
  specialties: [
    {
      name: "Orthopedics",
      href: "/orthopedics/",
      points: [
        "Focused on the assessment and management of musculoskeletal conditions affecting bones, joints, and mobility.",
        "Recommended when persistent groin pain and restricted hip movement continue despite treatment.",
      ],
    },
    {
      name: "Urology",
      href: "/urology/",
      points: [
        "Dedicated to the clinical assessment of urinary tract health and male reproductive wellbeing, with a strong emphasis on accurate diagnosis and patient comfort.",
        "Supports long-term health management by addressing underlying concerns and ensuring continuity of care through every stage.",
      ],
    },
    {
      name: "Gynecology",
      href: "/gynecology/",
      points: [
        "Provides comprehensive support for women’s health, including reproductive wellbeing, hormonal balance, and preventive care across different life stages.",
        "Focuses on early identification, personalised guidance, and ongoing health management to support long-term wellbeing.",
      ],
    },
    {
      name: "Ophthalmology",
      href: "/ophthalmology/",
      points: [
        "Specialised in the assessment and monitoring of eye health and vision, ensuring early detection of potential concerns.",
        "Aims to preserve and enhance visual function through continuous care and long-term management of eye conditions.",
      ],
    },
    {
      name: "Cosmetic Surgery",
      href: "/cosmetic/",
      points: [
        "Focused on enhancing physical appearance and individual confidence through carefully planned, medically guided care.",
        "Emphasises safety, personalised expectations, and achieving natural, balanced outcomes aligned with patient goals.",
      ],
    },
    {
      name: "Gastroenterology",
      href: "/gastrosurgery/",
      points: [
        "Dedicated to the evaluation of digestive system health, including conditions affecting the stomach, intestines, liver, and pancreas.",
        "Prioritises accurate diagnosis and long-term management to support overall digestive health and patient comfort.",
      ],
    },
    {
      name: "Cardiac Surgery",
      href: "/cardiac/",
      points: [
        "Focused on comprehensive evaluation of heart health and cardiovascular conditions through advanced clinical assessment.",
        "Supports long-term cardiac function and overall wellbeing through structured, patient-centred care pathways.",
      ],
    },
    {
      name: "Spine Surgery",
      href: "/spine/",
      points: [
        "Addresses conditions affecting the spine and nervous system with a focus on accurate evaluation and patient-specific care planning.",
        "Aims to improve comfort, restore functional ability, and support long-term mobility and quality of life.",
      ],
    },
    {
      name: "Surgical Oncology",
      href: "/oncology/",
      points: [
        "Focused on the clinical evaluation and management of cancer through early identification and coordinated care approaches.",
        "Emphasises multidisciplinary support, patient guidance, and long-term wellbeing throughout the care journey.",
      ],
    },
  ],
};

const diabeticPoints = [
  "Advised for individuals with vision complications caused by diabetes.",
  "Commonly associated with abnormal blood vessel growth or leakage in the retina.",
  "Recommended when there is progressive retinal damage affecting vision.",
];

const lungPoints = [
  "Advised for individuals requiring surgical treatment of lung cancer.",
  "Commonly associated with localized lung tumors.",
  "Recommended when the cancer is confined and operable.",
];

const smilePoints = [
  "Advised for individuals with multiple cosmetic flaws including crowding, discoloration, and missing teeth.",
  "Commonly associated with a comprehensive, multi-disciplinary approach to improving the appearance of the smile.",
];

export const specialties: SpecialtyPage[] = [
  {
    slug: "orthopedics",
    path: "/orthopedics/",
    documentTitle: "Orthopedics – New Journey Health",
    heroTitle: "Your Mobility, Restored with Expert Orthopedic Care",
    heroBody:
      "When movement hurts, life slows down. With advanced treatments, skilled specialists, and personalized care, regain strength, flexibility, and the freedom to move with confidence.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "Hip Replacement Surgery",
      "Knee Replacement Surgery",
      "Shoulder Replacement Surgery",
      "Arthroscopy & Minimally Invasive Surgery",
      "ACL (Anterior Cruciate Ligament) Treatment",
      "Meniscal Repair",
      "Hand and Wrist Surgery",
      "Foot and Ankle Surgery",
      "Sports Injury",
    ],
    comprehensiveHeading: "Comprehensive Orthopedic Solutions",
    image: media.modernMedicine,
    showFaqs: true,
    procedures: [
      p(
        "Hip Replacement Surgery",
        "Advised for individuals experiencing chronic joint pain, stiffness, or reduced mobility due to conditions like arthritis or injury.",
        "Commonly associated with conditions such as osteoarthritis, rheumatoid arthritis, or avascular necrosis.",
        "Recommended when persistent groin pain and restricted hip movement continue despite treatment.",
      ),
      p(
        "Knee Replacement Surgery",
        "Advised for individuals with significant knee joint deterioration affecting movement and stability.",
        "Commonly associated with severe degeneration, chronic inflammation, or post-traumatic joint damage.",
        "Recommended when pain, stiffness, and instability limit daily activities.",
      ),
      p(
        "Shoulder Replacement Surgery",
        "Advised for individuals with severe shoulder joint damage impacting arm mobility.",
        "Commonly associated with conditions such as rotator cuff tear arthropathy or complex fractures.",
        "Recommended when pain restricts overhead movement and routine activities.",
      ),
      p(
        "Arthroscopy & Minimally Invasive Surgery",
        "Advised for individuals requiring diagnosis and treatment of joint issues with minimal tissue disruption.",
        "Commonly associated with conditions such as loose bodies, impingement, or synovial inflammation.",
        "Recommended for precise diagnosis and targeted treatment with faster recovery.",
      ),
      p(
        "ACL (Anterior Cruciate Ligament) Treatment",
        "Advised for individuals with ligament injuries affecting joint stability.",
        "Commonly associated with acute injuries leading to instability or joint buckling.",
        "Recommended for active individuals aiming to restore strength, stability, and function.",
      ),
      p(
        "Meniscal Repair",
        "Advised for individuals requiring preservation of knee cartilage and joint cushioning.",
        "Commonly associated with meniscal tears such as longitudinal or bucket-handle types.",
        "Recommended when symptoms like knee locking, catching, or restricted movement are present.",
      ),
      p(
        "Hand and Wrist Surgery",
        "Advised for individuals experiencing pain, numbness, or reduced function in the hand and wrist.",
        "Commonly associated with conditions such as carpal tunnel syndrome, trigger finger, or fractures.",
        "Recommended when fine motor skills and daily activities are significantly affected.",
      ),
      p(
        "Foot and Ankle Surgery",
        "Advised for individuals with structural issues affecting foot and ankle function.",
        "Commonly associated with conditions such as bunions, tendon injuries, or fractures.",
        "Recommended when pain or deformity interferes with walking and weight-bearing activities.",
      ),
      p(
        "Sports Injury",
        "Advised for individuals with musculoskeletal injuries related to physical activity.",
        "Commonly associated with conditions such as stress fractures, dislocations, or tendon injuries.",
        "Recommended for individuals seeking a structured recovery to safely return to active lifestyles.",
      ),
    ],
  },
  {
    slug: "urology",
    path: "/urology/",
    documentTitle: "Urology – New Journey Health",
    heroTitle: "Expert Urology Care, Seamlessly Connected",
    heroBody:
      "Regain comfort and confidence with advanced urology care guided by international specialists. From diagnosis to recovery, every step is designed for precision, privacy, and the best outcomes.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "PCNL (Percutaneous Nephrolithotomy)",
      "ESWL (Shock Wave Lithotripsy)",
      "URS (Ureteroscopy)",
      "Cystoscopy",
      "TURP (Transurethral Resection of Prostate)",
      "Prostatectomy",
      "Nephrectomy",
      "Vasectomy",
      "Pyeloplasty",
    ],
    comprehensiveHeading: "Comprehensive Urological Solutions",
    comprehensiveIntro:
      "Complete care for urinary and reproductive health, ensuring accurate diagnosis, effective treatment, and recovery.",
    image: media.modernMedicine,
    showFaqs: true,
    procedures: [
      p(
        "PCNL (Percutaneous Nephrolithotomy)",
        "Advised for individuals with large or complex kidney stones affecting normal kidney function.",
        "Commonly associated with stones larger than 2 cm, staghorn calculi, or cases unresponsive to other treatments.",
        "Recommended when there is significant obstruction or a high stone burden.",
      ),
      p(
        "ESWL (Shock Wave Lithotripsy)",
        "Advised for individuals seeking non-invasive management of kidney or upper ureteral stones.",
        "Commonly associated with small to medium-sized stones.",
        "Recommended for individuals preferring treatment without surgical incisions.",
      ),
      p(
        "URS (Ureteroscopy)",
        "Advised for individuals requiring precise diagnosis and treatment of ureter-related conditions.",
        "Commonly associated with stones in the mid or lower ureter and certain abnormalities.",
        "Recommended when there is blockage, pain, or blood in the urine.",
      ),
      p(
        "Cystoscopy",
        "Advised for individuals requiring detailed examination of the bladder and urethra.",
        "Commonly associated with recurrent infections, bleeding, or suspected abnormalities.",
        "Recommended when accurate visualization of the lower urinary tract is needed.",
      ),
      p(
        "TURP (Transurethral Resection of Prostate)",
        "Advised for individuals experiencing urinary issues due to prostate enlargement.",
        "Commonly associated with benign prostatic hyperplasia causing obstruction.",
        "Recommended when symptoms such as weak flow, frequent urination, or urinary retention occur.",
      ),
      p(
        "Prostatectomy",
        "Advised for individuals requiring partial or complete removal of the prostate gland.",
        "Commonly associated with prostate cancer or severe enlargement.",
        "Recommended when definitive treatment or long-term symptom relief is necessary.",
      ),
      p(
        "Nephrectomy",
        "Advised for individuals requiring removal of a diseased or non-functioning kidney.",
        "Commonly associated with tumors, severe infections, or trauma.",
        "Recommended when preserving the kidney is not possible or safe.",
      ),
      p(
        "Vasectomy",
        "Advised for individuals seeking a permanent method of male contraception.",
        "Commonly associated with long-term family planning decisions.",
        "Recommended for individuals looking for a one-time, highly effective solution.",
      ),
      p(
        "Pyeloplasty",
        "Advised for individuals with structural blockages affecting urine flow from the kidney.",
        "Commonly associated with ureteropelvic junction obstruction leading to kidney swelling.",
        "Recommended when there is a risk of kidney damage due to poor drainage.",
      ),
    ],
  },
  {
    slug: "gynecology",
    path: "/gynecology/",
    documentTitle: "Gynecology – New Journey Health",
    heroTitle: "Compassionate Gynecology Care You Can Trust",
    heroBody:
      "Your health deserves expert attention at every stage. With experienced specialists and personalized care, receive treatment focused on comfort, safety, and long-term wellbeing.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "Open and Laparoscopic Myomectomy",
      "Open and Laparoscopic Hysterectomy",
      "Vaginal Hysterectomy",
      "Vaginal Vault Repair",
      "Cystocele Repair",
      "Ovarian Tumor Surgery",
      "Polypectomy",
      "Hysteroscopy",
      "Colposcopy",
    ],
    comprehensiveHeading: "Comprehensive Gynecological Solutions",
    comprehensiveIntro:
      "Complete care for women’s reproductive health, ensuring accurate diagnosis, effective treatment, and overall well-being.",
    image: media.fertility,
    showFaqs: true,
    procedures: [
      p(
        "Open and Laparoscopic Myomectomy",
        "Advised for individuals with uterine fibroids affecting menstrual cycles, fertility, or causing pelvic discomfort.",
        "Commonly associated with symptomatic leiomyomas leading to heavy bleeding or pressure symptoms.",
        "Recommended for individuals wishing to preserve the uterus for future fertility.",
      ),
      p(
        "Open and Laparoscopic Hysterectomy",
        "Advised for individuals requiring long-term management of severe uterine conditions impacting quality of life.",
        "Commonly associated with conditions such as adenomyosis, endometriosis, abnormal bleeding, or malignancies.",
        "Recommended when definitive treatment is required and other therapies have failed.",
      ),
      p(
        "Vaginal Hysterectomy",
        "Advised for individuals suitable for managing uterine conditions without abdominal incisions.",
        "Commonly associated with uterine prolapse or benign uterine disorders.",
        "Recommended for individuals eligible for a less invasive surgical approach.",
      ),
      p(
        "Vaginal Vault Repair",
        "Advised for individuals experiencing pelvic organ prolapse following hysterectomy.",
        "Commonly associated with weakening of pelvic support structures leading to vaginal vault prolapse.",
        "Recommended when there is discomfort, pressure, or functional impairment affecting daily activities.",
      ),
      p(
        "Cystocele Repair",
        "Advised for individuals with bladder displacement into the vaginal wall.",
        "Commonly associated with anterior vaginal wall prolapse due to weakened pelvic floor muscles.",
        "Recommended when urinary symptoms or visible bulging are present.",
      ),
      p(
        "Ovarian Tumor Surgery",
        "Advised for individuals with abnormal growths affecting the ovaries.",
        "Commonly associated with cysts, tumors, or suspected malignancies.",
        "Recommended when masses are large, persistent, or potentially cancerous.",
      ),
      p(
        "Polypectomy",
        "Advised for individuals with abnormal tissue growths within the uterus or cervix.",
        "Commonly associated with polyps causing irregular bleeding or fertility concerns.",
        "Recommended when localized growths are detected through imaging or evaluation.",
      ),
      p(
        "Hysteroscopy",
        "Advised for individuals requiring direct evaluation and treatment of intrauterine conditions.",
        "Commonly associated with fibroids, adhesions, or unexplained infertility.",
        "Recommended when detailed assessment of the uterine cavity is necessary.",
      ),
      p(
        "Colposcopy",
        "Advised for individuals requiring detailed examination of cervical abnormalities.",
        "Commonly associated with abnormal screening results or HPV-related changes.",
        "Recommended for further evaluation of suspicious cervical findings.",
      ),
    ],
  },
  {
    slug: "ophthalmology",
    path: "/ophthalmology/",
    documentTitle: "Ophthalmology – New Journey Health",
    heroTitle: "Clear Vision with World-Class Eye Care",
    heroBody:
      "See life more clearly with advanced ophthalmology treatments led by expert teams. Modern technology and precise care ensure the best results for your vision.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "Cataract Surgery",
      "Eye Muscle Repair",
      "Vitreoretinal Surgery",
      "LASIK and Refractive Surgery",
      "Glaucoma Surgery",
      "Pterygium Surgery",
      "Oculoplastic Surgery",
      "Diabetic Retinopathy",
      "Corneal Transplant and Keratoplasty",
    ],
    comprehensiveHeading: "Comprehensive Ophthalmology Solutions",
    comprehensiveIntro:
      "Complete care for eye health and vision, ensuring precise diagnosis, effective treatment, and long-term visual well-being.",
    image: media.wellness,
    showFaqs: true,
    procedures: [
      p(
        "Cataract Surgery",
        "Advised for individuals with reduced vision due to lens opacity affecting daily activities.",
        "Commonly associated with age-related changes, congenital conditions, or secondary lens clouding.",
        "Recommended when symptoms such as blurred vision, glare, or difficulty seeing at night interfere with quality of life.",
      ),
      p(
        "Eye Muscle Repair",
        "Advised for individuals with misalignment of the eyes affecting coordination and vision.",
        "Commonly associated with conditions such as strabismus or persistent double vision.",
        "Recommended when eye alignment impacts visual clarity or depth perception.",
      ),
      p(
        "Vitreoretinal Surgery",
        "Advised for individuals with serious conditions affecting the retina and vitreous.",
        "Commonly associated with retinal detachment, bleeding, or structural retinal disorders.",
        "Recommended when there is sudden vision loss or significant visual disturbances.",
      ),
      p(
        "LASIK and Refractive Surgery",
        "Advised for individuals seeking correction of vision and reduced dependence on glasses or contact lenses.",
        "Commonly associated with refractive errors such as nearsightedness, farsightedness, or astigmatism.",
        "Recommended for individuals looking for long-term vision correction.",
      ),
      p(
        "Glaucoma Surgery",
        "Advised for individuals with elevated eye pressure not adequately controlled by medication.",
        "Commonly associated with progressive glaucoma and risk to the optic nerve.",
        "Recommended when there is an ongoing risk of vision loss or optic nerve damage.",
      ),
      p(
        "Pterygium Surgery",
        "Advised for individuals with abnormal tissue growth on the eye surface.",
        "Commonly associated with irritation, redness, or obstruction of vision.",
        "Recommended when the growth affects vision or causes persistent discomfort.",
      ),
      p(
        "Oculoplastic Surgery",
        "Advised for individuals requiring restoration of function or appearance of the eyelids and surrounding structures.",
        "Commonly associated with drooping eyelids, inward turning lids, or tear duct blockages.",
        "Recommended when vision is obstructed or structural correction is necessary.",
      ),
      p("Diabetic Retinopathy", ...diabeticPoints),
      p("Corneal Transplant and Keratoplasty", ...diabeticPoints),
    ],
  },
  {
    slug: "cosmetic",
    path: "/cosmetic/",
    documentTitle: "Cosmetic – New Journey Health",
    heroTitle: "Confidence, Redefined with Cosmetic Expertise",
    heroBody:
      "Enhance your natural beauty with tailored cosmetic treatments. Skilled surgeons and advanced techniques help you achieve results that feel as good as they look.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "Rhinoplasty (Nose Surgery)",
      "Chin Augmentation (Genioplasty)",
      "Breast Augmentation / Reduction",
      "Liposuction & Body Contouring",
      "Gynecomastia Surgery",
      "Facelift & Anti-Aging Procedures",
      "Tummy Tuck (Abdominoplasty)",
      "Brazilian Butt Lift (BBL)",
      "Scar Revision Surgery",
    ],
    comprehensiveHeading: "Comprehensive Cosmetic Solutions",
    comprehensiveIntro:
      "Complete care for aesthetic enhancement and skin health, ensuring personalized treatments, safe procedures, and lasting results.",
    image: media.dental,
    showFaqs: true,
    procedures: [
      p(
        "Rhinoplasty (Nose Surgery)",
        "Advised for individuals seeking improvement in nasal shape or correction of breathing-related concerns.",
        "Advised for individuals seeking improvement in nasal shape or correction of breathing-related concerns.",
        "Recommended for individuals aiming for enhanced facial balance or improved airflow.",
      ),
      p(
        "Chin Augmentation (Genioplasty)",
        "Advised for individuals seeking enhancement of chin projection and overall facial harmony.",
        "Commonly associated with a recessed chin or imbalance in facial proportions.",
        "Recommended for individuals looking for a more defined jawline and profile.",
      ),
      p(
        "Breast Augmentation / Reduction",
        "Advised for individuals seeking modification of breast size, shape, or symmetry.",
        "Commonly associated with volume loss, overly large breasts, or disproportion.",
        "Recommended for individuals seeking aesthetic improvement or physical relief.",
      ),
      p(
        "Liposuction & Body Contouring",
        "Advised for individuals looking to remove stubborn fat deposits and refine body contours.",
        "Commonly associated with localized fat resistant to diet and exercise.",
        "Recommended for individuals at a stable weight seeking targeted body shaping.",
      ),
      p(
        "Gynecomastia Surgery",
        "Advised for individuals seeking reduction of excess male breast tissue and improved chest contour.",
        "Commonly associated with glandular enlargement or fat accumulation.",
        "Recommended for individuals experiencing discomfort or cosmetic concerns.",
      ),
      p(
        "Facelift & Anti-Aging Procedures",
        "Advised for individuals seeking restoration of youthful facial contours.",
        "Commonly associated with sagging skin, wrinkles, and loss of firmness.",
        "Recommended for individuals looking for long-term facial rejuvenation.",
      ),
      p(
        "Tummy Tuck (Abdominoplasty)",
        "Advised for individuals seeking improvement in abdominal contour and firmness.",
        "Commonly associated with loose skin or weakened abdominal muscles.",
        "Recommended after significant weight loss or pregnancy when natural tightening is insufficient.",
      ),
      p(
        "Brazilian Butt Lift (BBL)",
        "Advised for individuals seeking enhancement of buttock shape and volume using natural fat transfer.",
        "Commonly associated with flat or asymmetrical contours.",
        "Recommended for individuals looking for a fuller and more contoured appearance.",
      ),
      p(
        "Scar Revision Surgery",
        "Advised for individuals seeking improvement in the appearance or function of scars.",
        "Commonly associated with thick, raised, or restrictive scar tissue.",
        "Recommended for individuals with noticeable or uncomfortable scars.",
      ),
    ],
  },
  {
    slug: "gastrosurgery",
    path: "/gastrosurgery/",
    documentTitle: "Gastrosurgery – New Journey Health",
    heroTitle: "Advanced Gastro Surgery Care, Focused on You",
    heroBody:
      "Digestive health issues can impact every part of life. With expert-led gastro surgery, modern techniques, and personalized care, receive the right treatment at the right time for a smoother recovery and lasting relief.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "Hernia Surgery",
      "Gastric Bypass Surgery",
      "Gallbladder Surgery",
      "Pancreatic Surgery",
      "Colectomy",
      "ERCP",
      "Colonoscopy and Endoscopy",
      "Hemorrhoidectomy",
      "Fistula Surgery",
    ],
    comprehensiveHeading: "Comprehensive Gastrointestinal Care",
    comprehensiveIntro:
      "Complete care for digestive health, offering thorough diagnosis, personalized treatment, and continuous support for better comfort, recovery, and long-term wellness.",
    image: media.modernMedicine,
    showFaqs: true,
    procedures: [
      p(
        "Hernia Surgery",
        "Advised for individuals requiring repair of organ protrusions through the abdominal wall.",
        "Commonly associated with inguinal, umbilical, or incisional hernias.",
        "Recommended for individuals experiencing painful bulges or at risk of bowel complications.",
      ),
      p(
        "Gastric Bypass Surgery",
        "Advised for individuals seeking surgical support for significant weight loss.",
        "Commonly associated with morbid obesity and metabolic conditions such as Type 2 diabetes.",
        "Recommended for individuals with high BMI who have not responded to lifestyle interventions.",
      ),
      p(
        "Gallbladder Surgery",
        "Advised for individuals requiring removal of the gallbladder due to stones or inflammation.",
        "Commonly associated with gallstones (cholelithiasis) or cholecystitis.",
        "Recommended for individuals experiencing biliary colic or digestive complications.",
      ),
      p(
        "Pancreatic Surgery",
        "Advised for individuals with conditions affecting the pancreas.",
        "Commonly associated with pancreatic cancer, chronic pancreatitis, or cystic lesions.",
        "Recommended for individuals with localized tumors or severe inflammation.",
      ),
      p(
        "Colectomy",
        "Advised for individuals requiring removal of part or all of the colon.",
        "Commonly associated with colon cancer, diverticulitis, or inflammatory bowel disease.",
        "Recommended for individuals with malignant or severely diseased segments.",
      ),
      p(
        "ERCPERCP (Endoscopic Retrograde Cholangiopancreatography)",
        "Advised for individuals requiring combined endoscopic and imaging-based treatment of biliary or pancreatic duct conditions.",
        "Commonly associated with bile duct stones, strictures, or tumors.",
        "Recommended for individuals with jaundice or gallstone-related pancreatitis.",
      ),
      p(
        "Colonoscopy and Endoscopy",
        "Advised for individuals requiring internal evaluation of the gastrointestinal tract.",
        "Commonly associated with ulcers, polyps, bleeding, or early-stage cancers.",
        "Recommended for individuals undergoing colorectal cancer screening or evaluation of abdominal symptoms.",
      ),
      p(
        "Hemorrhoidectomy",
        "Advised for individuals requiring surgical removal of severe or prolapsed hemorrhoids.",
        "Commonly associated with advanced internal hemorrhoids or thrombosed external hemorrhoids.",
        "Recommended for individuals with persistent bleeding, pain, or failure of conservative treatments.",
      ),
      p(
        "Fistula Surgery",
        "Advised for individuals requiring correction of abnormal tunnels between the anal canal and skin.",
        "Commonly associated with anal fistulas following perianal abscesses.",
        "Recommended for individuals with recurrent drainage, pain, or infection.",
      ),
    ],
  },
  {
    slug: "cardiac",
    path: "/cardiac/",
    documentTitle: "Cardiac – New Journey Health",
    heroTitle: "Heart Care You Can Rely On",
    heroBody:
      "When it comes to your heart, timing matters. Access world-class cardiac care with experienced surgeons, advanced procedures, and a focus on safe, successful outcomes.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "CABG (Bypass Surgery)",
      "TAVR / TAVI",
      "Transcatheter Mitral Repair/Replacement",
      "ASD / VSD Closure",
      "Balloon Valvotomy",
      "Aortic Aneurysm Repair (EVAR/TEVAR)",
      "Coronary Angiography and Angioplasty",
      "Pacemaker and ICD Implantation",
      "Paediatric Heart Surgery",
    ],
    comprehensiveHeading: "Comprehensive Cardiology Solutions",
    comprehensiveIntro:
      "Complete care for heart health, providing precise diagnosis, personalized treatment, and ongoing support for optimal cardiovascular wellness.",
    image: media.modernMedicine,
    showFaqs: true,
    procedures: [
      p(
        "CABG (Bypass Surgery)",
        "Advised for individuals requiring restoration of blood flow around blocked coronary arteries.",
        "Commonly associated with severe coronary artery disease.",
        "Recommended for individuals with multiple arterial blockages or unsuccessful angioplasty.",
      ),
      p(
        "TAVR / TAVI",
        "Advised for individuals requiring minimally invasive aortic valve replacement.",
        "Commonly associated with severe aortic stenosis.",
        "Recommended for individuals at high surgical risk unsuitable for open-heart surgery.",
      ),
      p(
        "Transcatheter Mitral Repair/Replacement",
        "Advised for individuals requiring correction of mitral valve dysfunction.",
        "Commonly associated with mitral regurgitation or stenosis causing heart failure symptoms.",
        "Recommended for individuals with symptomatic mitral valve disease at high surgical risk.",
      ),
      p(
        "ASD / VSD Closure",
        "Advised for individuals requiring closure of congenital heart defects between chambers.",
        "Commonly associated with atrial or ventricular septal defects affecting blood flow.",
        "Recommended for individuals with significant defects requiring correction.",
      ),
      p(
        "Balloon Valvotomy",
        "Advised for individuals requiring widening of narrowed heart valves.",
        "Commonly associated with mitral, aortic, or pulmonary valve stenosis.",
        "Recommended for individuals with restricted blood flow due to stiff valve leaflets.",
      ),
      p(
        "Aortic Aneurysm Repair (EVAR/TEVAR)",
        "Advised for individuals requiring treatment of weakened or bulging sections of the aorta.",
        "Commonly associated with abdominal or thoracic aortic aneurysms at risk of rupture.",
        "Recommended for individuals with life-threatening arterial weakening.",
      ),
      p(
        "Coronary Angiography and Angioplasty",
        "Advised for individuals requiring visualization and treatment of narrowed coronary arteries.",
        "Commonly associated with heart attacks or angina.",
        "Recommended for individuals with suspected coronary blockages causing chest pain.",
      ),
      p(
        "Pacemaker and ICD Implantation",
        "Advised for individuals requiring management of abnormal heart rhythms.",
        "Commonly associated with bradycardia or life-threatening arrhythmias.",
        "Recommended for individuals with electrical conduction disorders or high cardiac risk.",
      ),
      p(
        "Paediatric Heart Surgery",
        "Advised for individuals (infants and children) requiring correction of congenital heart defects.",
        "Commonly associated with structural abnormalities such as Tetralogy of Fallot or valve malformations.",
        "Recommended for individuals with congenital heart conditions affecting normal function.",
      ),
    ],
  },
  {
    slug: "spine",
    path: "/spine/",
    documentTitle: "Spine – New Journey Health",
    heroTitle: "Spine Care That Gets You Moving Again",
    heroBody:
      "Back and spine issues can disrupt everyday life. With expert care and precise treatments, regain strength, flexibility, and freedom of movement.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "Laminectomy and Foraminotomy",
      "Discectomy and Microdiscectomy",
      "Spinal Osteotomy",
      "Spinal Fusion",
      "Artificial Disc Replacement",
      "Kyphoplasty / Vertebroplasty",
      "Endoscopic Spine Surgery",
      "Scoliosis Correction Surgery",
    ],
    comprehensiveHeading: "Comprehensive Spine Solutions",
    comprehensiveIntro:
      "Complete care for spinal health, offering thorough assessment, personalized treatment, and continuous support for improved mobility and pain relief.",
    image: media.modernMedicine,
    showFaqs: true,
    procedures: [
      p(
        "Laminectomy and Foraminotomy",
        "Advised for individuals requiring decompression of spinal nerves.",
        "Commonly associated with spinal stenosis and nerve root compression.",
        "Recommended for individuals experiencing leg pain, numbness, or neurogenic claudication.",
      ),
      p(
        "Discectomy and Microdiscectomy",
        "Advised for individuals requiring removal of herniated disc material.",
        "Commonly associated with herniated discs causing sciatica.",
        "Recommended for individuals with persistent sharp leg pain unresponsive to conservative care.",
      ),
      p(
        "Spinal Osteotomy",
        "Advised for individuals requiring correction of severe spinal alignment issues.",
        "Commonly associated with kyphosis or flat-back syndrome.",
        "Recommended for individuals with deformities affecting posture, mobility, or breathing.",
      ),
      p(
        "Spinal Fusion",
        "Advised for individuals requiring stabilization of the spine by joining vertebrae.",
        "Commonly associated with degenerative disc disease, spondylolisthesis, or instability.",
        "Recommended for individuals with chronic pain caused by abnormal spinal motion.",
      ),
      p(
        "Artificial Disc Replacement",
        "Advised for individuals requiring replacement of a damaged spinal disc while preserving motion.",
        "Commonly associated with degenerative disc disease.",
        "Recommended for individuals seeking to maintain spinal flexibility and avoid fusion.",
      ),
      p(
        "Kyphoplasty / Vertebroplasty",
        "Advised for individuals requiring stabilization of fractured vertebrae.",
        "Commonly associated with osteoporotic compression fractures.",
        "Recommended for individuals with severe localized back pain due to vertebral collapse.",
      ),
      p(
        "Endoscopic Spine Surgery",
        "Advised for individuals seeking minimally invasive treatment for spinal conditions.",
        "Commonly associated with disc herniations or localized spinal stenosis.",
        "Recommended for individuals preferring faster recovery with minimal tissue disruption.",
      ),
      p(
        "Scoliosis Correction Surgery",
        "Advised for individuals requiring correction of abnormal spinal curvature.",
        "Commonly associated with adolescent idiopathic scoliosis or degenerative spinal curves.",
        "Recommended for individuals with progressive deformities affecting function or appearance.",
      ),
    ],
  },
  {
    slug: "oncology",
    path: "/oncology/",
    documentTitle: "Oncology – New Journey Health",
    heroTitle: "Advanced Cancer Care, Centered Around You",
    heroBody:
      "Facing cancer is never easy, but the right care makes a difference. Benefit from advanced oncology treatments, expert teams, and compassionate support throughout your journey.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "Gastrointestinal/Colorectal Cancer",
      "Gynaecological Cancers",
      "Breast Cancer",
      "Pancreatic Cancer",
      "Lung Cancer",
      "Kidney Cancer",
      "Brain Tumors",
      "Liver Cancer",
      "Prostate Cancer",
    ],
    comprehensiveHeading: "Comprehensive Oncology Solutions",
    comprehensiveIntro:
      "Advanced care for cancer, offering thorough diagnosis, individualized treatment plans, and compassionate support at every stage.",
    image: media.modernMedicine,
    showFaqs: true,
    procedures: [
      p(
        "Gastrointestinal/Colorectal Cancer",
        "Advised for individuals requiring treatment of cancers affecting the digestive tract.",
        "Commonly associated with tumors in the stomach, colon, or rectum.",
        "Recommended for individuals diagnosed with malignant growths in the bowel.",
      ),
      p(
        "Gynaecological Cancers",
        "Advised for individuals requiring treatment of cancers affecting female reproductive organs.",
        "Commonly associated with uterine, cervical, or ovarian malignancies.",
        "Recommended for individuals diagnosed with early or advanced gynecological cancers.",
      ),
      p(
        "Breast Cancer",
        "Advised for individuals requiring management of cancerous growth in breast tissue.",
        "Commonly associated with abnormal lumps or biopsy-confirmed malignancy.",
        "Recommended for individuals requiring surgical removal or targeted treatment of tumors.",
      ),
      p(
        "Pancreatic Cancer",
        "Advised for individuals requiring treatment of cancers affecting the pancreas.",
        "Commonly associated with localized pancreatic tumors or certain advanced/metastatic conditions.",
        "Recommended when surgical removal (such as resection) is feasible for effective disease control.",
      ),
      p("Lung Cancer", ...lungPoints),
      p("Lung Cancer", ...lungPoints),
      p(
        "Kidney Cancer",
        "Advised for individuals requiring treatment of cancers affecting the Kidney or surrounding urinary structures.",
        "Commonly associated with renal masses, tumors, or abnormal growths detected in the kidneys.",
        "Recommended for individuals diagnosed through imaging (CT, MRI, ultrasound) or confirmed via biopsy.",
      ),
      p(
        "Brain Tumors",
        "Advised for individuals with abnormal growths within the brain requiring intervention.",
        "Commonly associated with neurological symptoms or imaging findings.",
        "Recommended when tumors affect brain function or increase intracranial pressure.",
      ),
      p(
        "Liver Cancer",
        "Advised for individuals requiring treatment of malignant tumors within the liver.",
        "Commonly associated with primary liver cancer or metastatic disease.",
        "Recommended when the disease is localized and surgically manageable.",
      ),
      p(
        "Prostate Cancer",
        "Advised for individuals requiring treatment of cancer in the prostate gland.",
        "Commonly associated with elevated PSA levels or confirmed malignancy.",
        "Recommended for individuals requiring definitive surgical or oncological management.",
      ),
    ],
  },
  {
    slug: "fertility",
    path: "/fertility/",
    documentTitle: "Fertility – New Journey Health",
    heroTitle: "World-Class Fertility Care, Without Borders",
    heroBody:
      "Take the next step in your parenthood journey with expert-led fertility and IVF care. With seamless coordination and advanced treatments, you’re supported every step of the way.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "Intrauterine Insemination (IUI)",
      "IVF (In Vitro Fertilization)",
      "ICSI (Intracytoplasmic Sperm Injection)",
      "IMSI (Intracytoplasmic Sperm Injection)",
      "Preimplantation Genetic Testing (PGT)",
      "Endometriosis-related Infertility Treatment",
      "Hysterosalpingography (HSG)",
      "Laparoscopic Ovarian Drilling (LOD)",
      "Frozen Embryo Transfer (FET)",
      "Sperm Retrieval (TESA / PESA / Micro-TESE)",
    ],
    comprehensiveHeading: "Comprehensive Fertility Solutions",
    comprehensiveIntro:
      "Complete care for reproductive health and conception, ensuring accurate diagnosis, personalized treatment, and ongoing support throughout the journey.",
    image: media.fertility,
    showFaqs: true,
    procedures: [
      p(
        "Intrauterine Insemination (IUI)",
        "Advised for individuals seeking an initial fertility treatment to improve chances of conception.",
        "Commonly associated with unexplained infertility, mild male factor issues, or cervical concerns.",
        "Recommended for individuals preferring a less invasive reproductive option.",
      ),
      p(
        "IVF (In Vitro Fertilization)",
        "Advised for individuals requiring advanced fertility support when natural conception is difficult.",
        "Commonly associated with tubal issues, endometriosis, or age-related fertility decline.",
        "Recommended for individuals who have not achieved success with simpler treatments.",
      ),
      p(
        "ICSI (Intracytoplasmic Sperm Injection)",
        "Advised for individuals requiring assisted fertilization in complex cases.",
        "Commonly associated with severe male infertility or poor sperm quality.",
        "Recommended when previous fertilization attempts have failed or significant sperm issues exist.",
      ),
      p(
        "Intracytoplasmic Morphologically Selected Sperm Injection (IMSI)",
        "Advised for individuals requiring advanced sperm selection techniques to enhance fertilization outcomes.",
        "Commonly associated with severe male infertility, recurrent IVF/ICSI failure, or high sperm DNA fragmentation.",
        "Recommended for individuals with repeated implantation failure or when improved sperm quality selection is needed.",
      ),
      p(
        "Preimplantation Genetic Testing (PGT)",
        "Advised for individuals seeking selection of genetically healthy embryos prior to pregnancy.",
        "Commonly associated with genetic disorders or chromosomal abnormalities.",
        "Recommended for individuals with known genetic risks or recurrent pregnancy loss.",
      ),
      p(
        "Endometriosis-related Infertility Treatment",
        "Advised for individuals experiencing fertility challenges due to endometrial tissue growth outside the uterus.",
        "Commonly associated with pelvic adhesions, cysts, or structural distortion.",
        "Recommended for individuals facing pain and difficulty conceiving.",
      ),
      p(
        "Hysterosalpingography (HSG)",
        "Advised for individuals undergoing diagnostic evaluation of fertility.",
        "Commonly associated with blocked fallopian tubes or uterine abnormalities.",
        "Recommended as part of initial infertility assessment.",
      ),
      p(
        "Laparoscopic Ovarian Drilling (LOD)",
        "Advised for individuals requiring restoration of ovulation in specific hormonal conditions.",
        "Commonly associated with polycystic ovary syndrome unresponsive to medication.",
        "Recommended when ovulation does not occur with standard treatments.",
      ),
      p(
        "Frozen Embryo Transfer (FET)",
        "Advised for individuals using previously preserved embryos for pregnancy.",
        "Commonly associated with IVF cycles or delayed implantation strategies.",
        "Recommended for individuals with stored embryos or specific clinical indications.",
      ),
      p(
        "Sperm Retrieval (TESA / PESA / Micro-TESE)",
        "Advised for individuals requiring retrieval of sperm when absent in the ejaculate.",
        "Commonly associated with obstructive or non-obstructive azoospermia.",
        "Recommended for individuals with sperm production or delivery challenges.",
      ),
    ],
  },
  {
    slug: "ayurveda-2",
    path: "/ayurveda-2/",
    documentTitle: "Ayurveda – New Journey Health",
    heroTitle: "Your Balance, Restored with Expert Ayurvedic Care",
    heroBody:
      "When body and mind feel out of harmony, daily life feels heavy. With personalized therapies, herbal treatments, and holistic guidance, restore wellness, vitality, and inner balance naturally.",
    introHeading: "Ayurveda: 5,000 years of holistic healing",
    introBody:
      "Traditional Indian system of medicine that promotes holistic well-being by balancing body, mind, and spirit. It focuses on the three doshas – Vata, Pitta, and Kapha – and uses herbal remedies, massage, diet, yoga, and meditation to restore health and harmony.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: [
      "Holistic Wellness Therapy",
      "Abhyanga Massage",
      "Panchakarma Therapy",
      "Udhvartan Treatment",
      "Shirodhara Treatment",
      "Potli Massage",
      "Kati Vasti",
      "Nasya Treatment",
      "Kashayadhara",
      "Pizhichil Treatment",
      "Ubtan",
    ],
    comprehensiveHeading: "Comprehensive Ayurvedic Therapies and Holistic Treatments",
    comprehensiveIntro:
      "Holistic care for body and mind, combining personalized therapies, herbal treatments, and lifestyle guidance to restore balance, health, and overall well-being.",
    image: media.ayurveda,
    showFaqs: true,
    procedures: [
      p(
        "Holistic Wellness Therapy",
        "Recommended for individuals seeking overall balance, vitality, and improved well-being.",
        "Commonly associated with weight management, anti-aging, geriatric care, women’s health, and nutritional healing.",
        "Combines personalized Ayurvedic therapies, herbal remedies, diet guidance, and lifestyle practices.",
        "Enhances physical strength, mental clarity, and long-term health naturally.",
      ),
      p(
        "Abhyanga Massage",
        "Recommended for individuals seeking relaxation, stress relief, and rejuvenation.",
        "Commonly associated with muscle tension, circulation issues, and dosha imbalance.",
        "Enhances circulation, eases muscle tension, and nourishes the skin using warm herbal oils applied with rhythmic full-body massage.",
      ),
      p(
        "Panchakarma Therapy",
        "Recommended for individuals seeking deep detoxification and restoration of internal balance.",
        "Commonly associated with chronic conditions, metabolic disorders, and general rejuvenation.",
        "Involves a series of five therapies (Vamana, Virechana, Basti, Nasya, Raktamokshana) to remove toxins and restore health.",
      ),
      p(
        "Udhvartan Treatment",
        "Recommended for individuals aiming for natural body cleansing and weight management.",
        "Commonly associated with excess fat, cellulite, and poor skin texture.",
        "Involves massaging herbal powders over the body in upward strokes to stimulate circulation and exfoliate the skin.",
      ),
      p(
        "Shirodhara Treatment",
        "Recommended for individuals experiencing stress, anxiety, or sleep disturbances.",
        "Commonly associated with mental fatigue, insomnia, or nervous system imbalance.",
        "Warm medicated oil flows continuously over the forehead to calm the mind and promote relaxation.",
      ),
      p(
        "Potli Massage",
        "Recommended for individuals seeking relief from muscle pain, stiffness, or joint discomfort.",
        "Commonly associated with arthritis and musculoskeletal issues.",
        "Warm herbal poultices are massaged to reduce pain and inflammation and improve mobility.",
      ),
      p(
        "Kati Vasti",
        "Recommended for individuals with lower back pain or spinal stiffness.",
        "Commonly associated with disc problems, muscle strain, or chronic back discomfort.",
        "Warm medicated oil is retained over the lower back using a dough ring to ease pain.",
      ),
      p(
        "Nasya Treatment",
        "Recommended for individuals seeking relief from sinus or respiratory issues.",
        "Commonly associated with headaches, allergies, or nasal congestion.",
        "Medicated oils are administered through the nostrils to promote clearer breathing and mental clarity.",
      ),
      p(
        "Kashayadhara",
        "Recommended for individuals aiming for skin health and internal detoxification.",
        "Commonly associated with inflammation or skin-related issues.",
        "Warm herbal decoctions are poured continuously over the body to purify and rejuvenate.",
      ),
      p(
        "Pizhichil Treatment",
        "Recommended for individuals seeking joint strengthening and nervous system relaxation.",
        "Commonly associated with arthritis-related pain or fatigue.",
        "Warm medicated oil is poured while performing synchronized massage to improve vitality and relieve pain.",
      ),
      p(
        "Ubtan",
        "Recommended for individuals seeking natural skin care and beautification.",
        "Commonly associated with dull skin, uneven tone, or chemical sensitivity.",
        "Herbal pastes are applied and gently scrubbed on the skin to enhance texture and radiance.",
      ),
    ],
  },
  {
    slug: "dental-2",
    path: "/dental-2/",
    documentTitle: "Dental – New Journey Health",
    heroTitle: "Your Smile, Perfected by Expert Dentists",
    heroBody:
      "Experience premium dental care led by top dentists, offering personalized treatments designed for your comfort, confidence, and the best results.",
    treatmentsHeading: "Treatments we offer",
    treatmentNames: ["Dental Implants", "Dental Veneers", "Smile Makeover"],
    comprehensiveHeading: "Comprehensive Dental Solutions",
    comprehensiveIntro:
      "Enhance your smile with expert dental care – advanced treatments, skilled professionals, and world-class results at a fraction of global costs.",
    image: media.dental,
    showFaqs: true,
    procedures: [
      p(
        "Dental Veneers",
        "Advised for individuals with chipped, stained, misaligned, or unevenly spaced teeth.",
        "Commonly associated with those seeking cosmetic dental improvements for smile enhancement.",
        "Recommended when a significant aesthetic upgrade in tooth color, shape, and overall appearance is desired.",
      ),
      p(
        "Dental Implants",
        ...smilePoints,
        "Commonly associated with a comprehensive, multi-disciplinary approach to improving the appearance of the smile.",
      ),
      p(
        "Maxillofacial Surgery",
        "Advised for individuals with facial trauma, jaw deformities, or congenital anomalies affecting function and appearance.",
        "Commonly involves a multidisciplinary approach integrating oral surgery, orthodontics, and reconstructive techniques.",
        "Recommended for individuals requiring correction of facial structure, bite alignment, or complex conditions impacting speech, chewing, or aesthetics.",
      ),
      p(
        "Smile Makeover",
        ...smilePoints,
        "Recommended for individuals requiring a customized combination of procedures for a total dental transformation.",
      ),
    ],
  },
];

export function getSpecialty(slug: string) {
  return specialties.find((s) => s.slug === slug);
}
